/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Appointment = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'notes' : IDL.Text,
  'patientName' : IDL.Text,
  'dateTime' : Timestamp,
});
export const BookingStatus = IDL.Variant({
  'ReportUploaded' : IDL.Null,
  'Confirmed' : IDL.Null,
  'Booked' : IDL.Null,
  'InProgress' : IDL.Null,
  'Completed' : IDL.Null,
});
export const BookingStatusEntry = IDL.Record({
  'status' : BookingStatus,
  'note' : IDL.Text,
  'timestamp' : Timestamp,
});
export const DiagnosticBooking = IDL.Record({
  'id' : IDL.Text,
  'reportUrl' : IDL.Opt(IDL.Text),
  'status' : BookingStatus,
  'createdAt' : Timestamp,
  'testType' : IDL.Text,
  'statusHistory' : IDL.Vec(BookingStatusEntry),
  'reportUploadedAt' : IDL.Opt(Timestamp),
  'patientPrincipal' : IDL.Principal,
  'preferredDate' : IDL.Text,
  'labPrincipal' : IDL.Principal,
  'reason' : IDL.Opt(IDL.Text),
});
export const MedicineCategory = IDL.Variant({
  'Liquid' : IDL.Null,
  'Capsule' : IDL.Null,
  'Injection' : IDL.Null,
  'Tablet' : IDL.Null,
  'Topical' : IDL.Null,
  'Other' : IDL.Null,
});
export const InventoryItem = IDL.Record({
  'id' : IDL.Text,
  'stockQuantity' : IDL.Nat,
  'expiryDate' : Timestamp,
  'minThreshold' : IDL.Nat,
  'lastUpdated' : Timestamp,
  'pharmacyPrincipal' : IDL.Principal,
  'category' : MedicineCategory,
  'maxThreshold' : IDL.Nat,
  'medicineName' : IDL.Text,
});
export const Medicine = IDL.Record({
  'id' : IDL.Text,
  'dosage' : IDL.Text,
  'expiryDate' : Timestamp,
  'ownerPrincipal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'category' : MedicineCategory,
  'frequency' : IDL.Text,
  'prescriptionUrl' : IDL.Opt(IDL.Text),
});
export const OrderStatus = IDL.Variant({
  'Delivered' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Shipped' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : OrderStatus,
  'patientId' : IDL.Text,
  'deliveryDate' : IDL.Opt(Timestamp),
  'orderDate' : Timestamp,
  'quantity' : IDL.Nat,
  'pharmacyId' : IDL.Text,
  'medicineName' : IDL.Text,
});
export const Reminder = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : Timestamp,
  'voiceEnabled' : IDL.Bool,
  'isEnabled' : IDL.Bool,
  'reminderTime' : IDL.Text,
  'userPrincipal' : IDL.Principal,
  'medicineId' : IDL.Text,
});
export const Report = IDL.Record({
  'id' : IDL.Text,
  'patientId' : IDL.Text,
  'reportType' : IDL.Text,
  'uploadDate' : Timestamp,
  'labPrincipal' : IDL.Principal,
  'fileUrl' : IDL.Text,
});
export const ExportLogEntry = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'userRole' : IDL.Text,
  'userId' : IDL.Principal,
  'errorMessage' : IDL.Opt(IDL.Text),
  'fileSizeBytes' : IDL.Opt(IDL.Nat),
  'exportType' : IDL.Text,
  'fileType' : IDL.Text,
  'filename' : IDL.Text,
  'timestamp' : IDL.Int,
  'filtersApplied' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'Lab' : IDL.Null,
  'Pharmacy' : IDL.Null,
  'Admin' : IDL.Null,
  'Patient' : IDL.Null,
  'Hospital' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Text,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'role' : UserRole,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'telegramEnabled' : IDL.Bool,
  'phone' : IDL.Opt(IDL.Text),
  'registrationDate' : Timestamp,
  'telegramChatId' : IDL.Opt(IDL.Text),
});
export const ActivityActorRole = IDL.Variant({
  'Diagnostic' : IDL.Null,
  'Pharmacy' : IDL.Null,
  'Admin' : IDL.Null,
  'Patient' : IDL.Null,
  'Hospital' : IDL.Null,
});
export const ActivityEventType = IDL.Variant({
  'ConsentGranted' : IDL.Null,
  'ReportCompleted' : IDL.Null,
  'SystemAlert' : IDL.Null,
  'InventoryStatusChanged' : IDL.Null,
  'DiagnosticBooked' : IDL.Null,
  'ConsentAccessGranted' : IDL.Null,
  'PatientAdherenceViewed' : IDL.Null,
  'RestockFulfilled' : IDL.Null,
  'ReminderCreated' : IDL.Null,
  'ReportUploaded' : IDL.Null,
  'TestProcessingStarted' : IDL.Null,
  'TelegramDisconnected' : IDL.Null,
  'HospitalMedicineAdded' : IDL.Null,
  'ReminderMissed' : IDL.Null,
  'HospitalInventoryUpdated' : IDL.Null,
  'CSVUploaded' : IDL.Null,
  'TelegramConnected' : IDL.Null,
  'BookingAccepted' : IDL.Null,
  'MedicineAddedManually' : IDL.Null,
  'BookingReceived' : IDL.Null,
  'ExpiryAlertTriggered' : IDL.Null,
  'ExpiryWarningTriggered' : IDL.Null,
  'ConsentRevoked' : IDL.Null,
  'EcosystemSyncStats' : IDL.Null,
  'DoseMarkedTaken' : IDL.Null,
  'UserCreated' : IDL.Null,
  'ConsentAccessRevoked' : IDL.Null,
  'MedicineSold' : IDL.Null,
  'MedicineSyncedToPatient' : IDL.Null,
  'RoleChanged' : IDL.Null,
  'ReportViewedDownloaded' : IDL.Null,
  'ReminderCompleted' : IDL.Null,
  'InventoryItemAdded' : IDL.Null,
  'SampleCollected' : IDL.Null,
  'MedicineSyncedFromPharmacy' : IDL.Null,
  'QRScanCompleted' : IDL.Null,
});
export const ActivityEventView = IDL.Record({
  'id' : IDL.Text,
  'metadata' : IDL.Opt(IDL.Text),
  'resourceId' : IDL.Opt(IDL.Text),
  'eventActor' : IDL.Record({
    'role' : ActivityActorRole,
    'principalId' : IDL.Principal,
  }),
  'timestamp' : IDL.Int,
  'eventType' : ActivityEventType,
  'readBy' : IDL.Vec(IDL.Principal),
});
export const ConsentAuditEntry = IDL.Record({
  'field' : IDL.Text,
  'action' : IDL.Text,
  'timestamp' : Timestamp,
});
export const ConsentRecord = IDL.Record({
  'id' : IDL.Text,
  'lastUpdated' : Timestamp,
  'adherenceSharing' : IDL.Bool,
  'patientPrincipal' : IDL.Principal,
  'diagnosticAccess' : IDL.Bool,
  'auditTrail' : IDL.Vec(ConsentAuditEntry),
  'prescriptionSharing' : IDL.Bool,
});
export const DoseLog = IDL.Record({
  'id' : IDL.Text,
  'isOnTime' : IDL.Bool,
  'takenAt' : Timestamp,
  'userPrincipal' : IDL.Principal,
  'medicineId' : IDL.Text,
});
export const NotifType = IDL.Variant({
  'BookingCompleted' : IDL.Null,
  'ConsentChanged' : IDL.Null,
  'ReminderMissed' : IDL.Null,
  'ReportReady' : IDL.Null,
  'MedicineSynced' : IDL.Null,
  'BookingConfirmed' : IDL.Null,
  'LowStock' : IDL.Null,
  'ExpiringSoon' : IDL.Null,
});
export const NotificationRecord = IDL.Record({
  'id' : IDL.Text,
  'notifType' : NotifType,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'relatedId' : IDL.Opt(IDL.Text),
  'recipientPrincipal' : IDL.Principal,
});
export const SyncedMedicine = IDL.Record({
  'id' : IDL.Text,
  'sourcePharmacy' : IDL.Text,
  'dosage' : IDL.Text,
  'purchaseTimestamp' : Timestamp,
  'expiryDate' : Timestamp,
  'ownerPrincipal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'batchNumber' : IDL.Text,
  'category' : MedicineCategory,
  'frequency' : IDL.Text,
  'sourcePrincipal' : IDL.Principal,
  'prescriptionUrl' : IDL.Opt(IDL.Text),
});
export const PharmacySyncLog = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'Failed' : IDL.Null,
    'Duplicate' : IDL.Null,
    'Success' : IDL.Null,
  }),
  'expiryDate' : Timestamp,
  'errorMessage' : IDL.Opt(IDL.Text),
  'pharmacyPrincipal' : IDL.Principal,
  'patientPrincipal' : IDL.Principal,
  'syncedAt' : Timestamp,
  'batchNumber' : IDL.Text,
  'quantity' : IDL.Nat,
  'medicineName' : IDL.Text,
});
export const ReportDataPoint = IDL.Record({
  'value' : IDL.Text,
  'metadata' : IDL.Opt(IDL.Text),
  'dataLabel' : IDL.Text,
});
export const ReportData = IDL.Record({
  'generatedAt' : IDL.Int,
  'reportType' : IDL.Text,
  'dataPoints' : IDL.Vec(ReportDataPoint),
});
export const TelegramLog = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'errorMessage' : IDL.Opt(IDL.Text),
  'reminderTime' : IDL.Text,
  'userPrincipal' : IDL.Principal,
  'timestamp' : IDL.Int,
  'medicineId' : IDL.Text,
  'medicineName' : IDL.Text,
});
export const WorkflowStage = IDL.Record({
  'status' : IDL.Text,
  'actorRole' : IDL.Text,
  'events' : IDL.Vec(ActivityEventView),
  'stageType' : IDL.Text,
});
export const WorkflowChain = IDL.Record({
  'stages' : IDL.Vec(WorkflowStage),
  'medicine' : IDL.Opt(IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text })),
});
export const LogExportRequest = IDL.Record({
  'status' : IDL.Text,
  'userRole' : IDL.Text,
  'errorMessage' : IDL.Opt(IDL.Text),
  'fileSizeBytes' : IDL.Opt(IDL.Nat),
  'exportType' : IDL.Text,
  'fileType' : IDL.Text,
  'filename' : IDL.Text,
  'filtersApplied' : IDL.Text,
});
export const AuditSearchQuery = IDL.Record({
  'toTimestamp' : IDL.Opt(IDL.Int),
  'fromTimestamp' : IDL.Opt(IDL.Int),
  'role' : IDL.Opt(IDL.Text),
  'offset' : IDL.Nat,
  'limit' : IDL.Nat,
  'searchText' : IDL.Opt(IDL.Text),
  'severity' : IDL.Opt(IDL.Text),
  'eventType' : IDL.Opt(IDL.Text),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createAppointment' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Text],
      [IDL.Variant({ 'ok' : Appointment, 'err' : IDL.Text })],
      [],
    ),
  'createDiagnosticBooking' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : DiagnosticBooking, 'err' : IDL.Text })],
      [],
    ),
  'createInventoryItem' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Int, MedicineCategory],
      [IDL.Variant({ 'ok' : InventoryItem, 'err' : IDL.Text })],
      [],
    ),
  'createMedicine' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int, MedicineCategory],
      [IDL.Variant({ 'ok' : Medicine, 'err' : IDL.Text })],
      [],
    ),
  'createOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : Order, 'err' : IDL.Text })],
      [],
    ),
  'createReminder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : Reminder, 'err' : IDL.Text })],
      [],
    ),
  'createReport' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Report, 'err' : IDL.Text })],
      [],
    ),
  'deleteExportLog' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteInventoryItem' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteMedicine' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteReminder' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getAdherenceScore' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'getAllExportLogs' : IDL.Func([], [IDL.Vec(ExportLogEntry)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAuditEventsByActor' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ActivityEventView)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getConsentAuditTrail' : IDL.Func(
      [],
      [IDL.Vec(ConsentAuditEntry)],
      ['query'],
    ),
  'getConsentedPatients' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({ 'patient' : UserProfile, 'consent' : ConsentRecord })
        ),
      ],
      ['query'],
    ),
  'getDiagnosticBooking' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DiagnosticBooking)],
      ['query'],
    ),
  'getEventById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ActivityEventView)],
      ['query'],
    ),
  'getExpiryStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'expiringSoon' : IDL.Nat,
          'expired' : IDL.Nat,
          'safe' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getExportAnalytics' : IDL.Func(
      [],
      [
        IDL.Record({
          'successCount' : IDL.Nat,
          'failureCount' : IDL.Nat,
          'totalExports' : IDL.Nat,
          'exportsByRole' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          'exportsByType' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          'exportsByFormat' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
        }),
      ],
      ['query'],
    ),
  'getInventoryStats' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getLabDiagnosticBookings' : IDL.Func(
      [],
      [IDL.Vec(DiagnosticBooking)],
      ['query'],
    ),
  'getLabReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'getMedicineLcChain' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ActivityEventView)],
      ['query'],
    ),
  'getMyConsent' : IDL.Func([], [IDL.Opt(ConsentRecord)], ['query']),
  'getMyDiagnosticBookings' : IDL.Func(
      [],
      [IDL.Vec(DiagnosticBooking)],
      ['query'],
    ),
  'getMyDoseLogs' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(DoseLog)],
      ['query'],
    ),
  'getMyExportLogs' : IDL.Func([], [IDL.Vec(ExportLogEntry)], ['query']),
  'getMyMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(NotificationRecord)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getMyProfile' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      ['query'],
    ),
  'getMyReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
  'getMyReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'getMySyncedMedicines' : IDL.Func([], [IDL.Vec(SyncedMedicine)], ['query']),
  'getMyTimeline' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(ActivityEventView)],
      ['query'],
    ),
  'getPharmacyInventory' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getPharmacyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getPharmacySyncLogs' : IDL.Func([], [IDL.Vec(PharmacySyncLog)], ['query']),
  'getReportData' : IDL.Func([IDL.Text], [ReportData], ['query']),
  'getSystemStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalOrders' : IDL.Nat,
          'totalUsers' : IDL.Nat,
          'totalMedicines' : IDL.Nat,
          'usersByRole' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
        }),
      ],
      ['query'],
    ),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTelegramLogs' : IDL.Func([], [IDL.Vec(TelegramLog)], ['query']),
  'getWorkflowChain' : IDL.Func([IDL.Text], [WorkflowChain], ['query']),
  'isBotTokenConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logDose' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Bool],
      [IDL.Variant({ 'ok' : DoseLog, 'err' : IDL.Text })],
      [],
    ),
  'logExport' : IDL.Func([LogExportRequest], [ExportLogEntry], []),
  'lookupPatientByPhone' : IDL.Func(
      [IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({ 'principal' : IDL.Principal, 'name' : IDL.Text }),
          'err' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'markAllNotificationsRead' : IDL.Func([], [IDL.Nat], []),
  'markEventRead' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'markNotificationRead' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, UserRole],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      [],
    ),
  'revokeAllConsent' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : ConsentRecord, 'err' : IDL.Text })],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchAuditLog' : IDL.Func(
      [AuditSearchQuery],
      [IDL.Vec(ActivityEventView)],
      ['query'],
    ),
  'sendTestTelegramMessage' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setBotToken' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'syncMedicineToPatient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Nat],
      [IDL.Variant({ 'ok' : PharmacySyncLog, 'err' : IDL.Text })],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAppointmentStatus' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Appointment, 'err' : IDL.Text })],
      [],
    ),
  'updateConsent' : IDL.Func(
      [IDL.Bool, IDL.Bool, IDL.Bool],
      [IDL.Variant({ 'ok' : ConsentRecord, 'err' : IDL.Text })],
      [],
    ),
  'updateDiagnosticBookingStatus' : IDL.Func(
      [IDL.Text, BookingStatus, IDL.Text],
      [IDL.Variant({ 'ok' : DiagnosticBooking, 'err' : IDL.Text })],
      [],
    ),
  'updateInventoryItem' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Int],
      [IDL.Variant({ 'ok' : InventoryItem, 'err' : IDL.Text })],
      [],
    ),
  'updateMedicine' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int, MedicineCategory],
      [IDL.Variant({ 'ok' : Medicine, 'err' : IDL.Text })],
      [],
    ),
  'updateMedicinePrescriptionUrl' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateOrderStatus' : IDL.Func(
      [IDL.Text, OrderStatus],
      [IDL.Variant({ 'ok' : Order, 'err' : IDL.Text })],
      [],
    ),
  'updateReminder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool, IDL.Bool],
      [IDL.Variant({ 'ok' : Reminder, 'err' : IDL.Text })],
      [],
    ),
  'updateTelegramSettings' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Bool)],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      [],
    ),
  'updateUserProfile' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Bool),
      ],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      [],
    ),
  'updateUserStatus' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'uploadDiagnosticReport' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : DiagnosticBooking, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Appointment = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'notes' : IDL.Text,
    'patientName' : IDL.Text,
    'dateTime' : Timestamp,
  });
  const BookingStatus = IDL.Variant({
    'ReportUploaded' : IDL.Null,
    'Confirmed' : IDL.Null,
    'Booked' : IDL.Null,
    'InProgress' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const BookingStatusEntry = IDL.Record({
    'status' : BookingStatus,
    'note' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const DiagnosticBooking = IDL.Record({
    'id' : IDL.Text,
    'reportUrl' : IDL.Opt(IDL.Text),
    'status' : BookingStatus,
    'createdAt' : Timestamp,
    'testType' : IDL.Text,
    'statusHistory' : IDL.Vec(BookingStatusEntry),
    'reportUploadedAt' : IDL.Opt(Timestamp),
    'patientPrincipal' : IDL.Principal,
    'preferredDate' : IDL.Text,
    'labPrincipal' : IDL.Principal,
    'reason' : IDL.Opt(IDL.Text),
  });
  const MedicineCategory = IDL.Variant({
    'Liquid' : IDL.Null,
    'Capsule' : IDL.Null,
    'Injection' : IDL.Null,
    'Tablet' : IDL.Null,
    'Topical' : IDL.Null,
    'Other' : IDL.Null,
  });
  const InventoryItem = IDL.Record({
    'id' : IDL.Text,
    'stockQuantity' : IDL.Nat,
    'expiryDate' : Timestamp,
    'minThreshold' : IDL.Nat,
    'lastUpdated' : Timestamp,
    'pharmacyPrincipal' : IDL.Principal,
    'category' : MedicineCategory,
    'maxThreshold' : IDL.Nat,
    'medicineName' : IDL.Text,
  });
  const Medicine = IDL.Record({
    'id' : IDL.Text,
    'dosage' : IDL.Text,
    'expiryDate' : Timestamp,
    'ownerPrincipal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'category' : MedicineCategory,
    'frequency' : IDL.Text,
    'prescriptionUrl' : IDL.Opt(IDL.Text),
  });
  const OrderStatus = IDL.Variant({
    'Delivered' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Shipped' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : OrderStatus,
    'patientId' : IDL.Text,
    'deliveryDate' : IDL.Opt(Timestamp),
    'orderDate' : Timestamp,
    'quantity' : IDL.Nat,
    'pharmacyId' : IDL.Text,
    'medicineName' : IDL.Text,
  });
  const Reminder = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : Timestamp,
    'voiceEnabled' : IDL.Bool,
    'isEnabled' : IDL.Bool,
    'reminderTime' : IDL.Text,
    'userPrincipal' : IDL.Principal,
    'medicineId' : IDL.Text,
  });
  const Report = IDL.Record({
    'id' : IDL.Text,
    'patientId' : IDL.Text,
    'reportType' : IDL.Text,
    'uploadDate' : Timestamp,
    'labPrincipal' : IDL.Principal,
    'fileUrl' : IDL.Text,
  });
  const ExportLogEntry = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'userRole' : IDL.Text,
    'userId' : IDL.Principal,
    'errorMessage' : IDL.Opt(IDL.Text),
    'fileSizeBytes' : IDL.Opt(IDL.Nat),
    'exportType' : IDL.Text,
    'fileType' : IDL.Text,
    'filename' : IDL.Text,
    'timestamp' : IDL.Int,
    'filtersApplied' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'Lab' : IDL.Null,
    'Pharmacy' : IDL.Null,
    'Admin' : IDL.Null,
    'Patient' : IDL.Null,
    'Hospital' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Text,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'role' : UserRole,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'telegramEnabled' : IDL.Bool,
    'phone' : IDL.Opt(IDL.Text),
    'registrationDate' : Timestamp,
    'telegramChatId' : IDL.Opt(IDL.Text),
  });
  const ActivityActorRole = IDL.Variant({
    'Diagnostic' : IDL.Null,
    'Pharmacy' : IDL.Null,
    'Admin' : IDL.Null,
    'Patient' : IDL.Null,
    'Hospital' : IDL.Null,
  });
  const ActivityEventType = IDL.Variant({
    'ConsentGranted' : IDL.Null,
    'ReportCompleted' : IDL.Null,
    'SystemAlert' : IDL.Null,
    'InventoryStatusChanged' : IDL.Null,
    'DiagnosticBooked' : IDL.Null,
    'ConsentAccessGranted' : IDL.Null,
    'PatientAdherenceViewed' : IDL.Null,
    'RestockFulfilled' : IDL.Null,
    'ReminderCreated' : IDL.Null,
    'ReportUploaded' : IDL.Null,
    'TestProcessingStarted' : IDL.Null,
    'TelegramDisconnected' : IDL.Null,
    'HospitalMedicineAdded' : IDL.Null,
    'ReminderMissed' : IDL.Null,
    'HospitalInventoryUpdated' : IDL.Null,
    'CSVUploaded' : IDL.Null,
    'TelegramConnected' : IDL.Null,
    'BookingAccepted' : IDL.Null,
    'MedicineAddedManually' : IDL.Null,
    'BookingReceived' : IDL.Null,
    'ExpiryAlertTriggered' : IDL.Null,
    'ExpiryWarningTriggered' : IDL.Null,
    'ConsentRevoked' : IDL.Null,
    'EcosystemSyncStats' : IDL.Null,
    'DoseMarkedTaken' : IDL.Null,
    'UserCreated' : IDL.Null,
    'ConsentAccessRevoked' : IDL.Null,
    'MedicineSold' : IDL.Null,
    'MedicineSyncedToPatient' : IDL.Null,
    'RoleChanged' : IDL.Null,
    'ReportViewedDownloaded' : IDL.Null,
    'ReminderCompleted' : IDL.Null,
    'InventoryItemAdded' : IDL.Null,
    'SampleCollected' : IDL.Null,
    'MedicineSyncedFromPharmacy' : IDL.Null,
    'QRScanCompleted' : IDL.Null,
  });
  const ActivityEventView = IDL.Record({
    'id' : IDL.Text,
    'metadata' : IDL.Opt(IDL.Text),
    'resourceId' : IDL.Opt(IDL.Text),
    'eventActor' : IDL.Record({
      'role' : ActivityActorRole,
      'principalId' : IDL.Principal,
    }),
    'timestamp' : IDL.Int,
    'eventType' : ActivityEventType,
    'readBy' : IDL.Vec(IDL.Principal),
  });
  const ConsentAuditEntry = IDL.Record({
    'field' : IDL.Text,
    'action' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const ConsentRecord = IDL.Record({
    'id' : IDL.Text,
    'lastUpdated' : Timestamp,
    'adherenceSharing' : IDL.Bool,
    'patientPrincipal' : IDL.Principal,
    'diagnosticAccess' : IDL.Bool,
    'auditTrail' : IDL.Vec(ConsentAuditEntry),
    'prescriptionSharing' : IDL.Bool,
  });
  const DoseLog = IDL.Record({
    'id' : IDL.Text,
    'isOnTime' : IDL.Bool,
    'takenAt' : Timestamp,
    'userPrincipal' : IDL.Principal,
    'medicineId' : IDL.Text,
  });
  const NotifType = IDL.Variant({
    'BookingCompleted' : IDL.Null,
    'ConsentChanged' : IDL.Null,
    'ReminderMissed' : IDL.Null,
    'ReportReady' : IDL.Null,
    'MedicineSynced' : IDL.Null,
    'BookingConfirmed' : IDL.Null,
    'LowStock' : IDL.Null,
    'ExpiringSoon' : IDL.Null,
  });
  const NotificationRecord = IDL.Record({
    'id' : IDL.Text,
    'notifType' : NotifType,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'relatedId' : IDL.Opt(IDL.Text),
    'recipientPrincipal' : IDL.Principal,
  });
  const SyncedMedicine = IDL.Record({
    'id' : IDL.Text,
    'sourcePharmacy' : IDL.Text,
    'dosage' : IDL.Text,
    'purchaseTimestamp' : Timestamp,
    'expiryDate' : Timestamp,
    'ownerPrincipal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'batchNumber' : IDL.Text,
    'category' : MedicineCategory,
    'frequency' : IDL.Text,
    'sourcePrincipal' : IDL.Principal,
    'prescriptionUrl' : IDL.Opt(IDL.Text),
  });
  const PharmacySyncLog = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'Failed' : IDL.Null,
      'Duplicate' : IDL.Null,
      'Success' : IDL.Null,
    }),
    'expiryDate' : Timestamp,
    'errorMessage' : IDL.Opt(IDL.Text),
    'pharmacyPrincipal' : IDL.Principal,
    'patientPrincipal' : IDL.Principal,
    'syncedAt' : Timestamp,
    'batchNumber' : IDL.Text,
    'quantity' : IDL.Nat,
    'medicineName' : IDL.Text,
  });
  const ReportDataPoint = IDL.Record({
    'value' : IDL.Text,
    'metadata' : IDL.Opt(IDL.Text),
    'dataLabel' : IDL.Text,
  });
  const ReportData = IDL.Record({
    'generatedAt' : IDL.Int,
    'reportType' : IDL.Text,
    'dataPoints' : IDL.Vec(ReportDataPoint),
  });
  const TelegramLog = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'errorMessage' : IDL.Opt(IDL.Text),
    'reminderTime' : IDL.Text,
    'userPrincipal' : IDL.Principal,
    'timestamp' : IDL.Int,
    'medicineId' : IDL.Text,
    'medicineName' : IDL.Text,
  });
  const WorkflowStage = IDL.Record({
    'status' : IDL.Text,
    'actorRole' : IDL.Text,
    'events' : IDL.Vec(ActivityEventView),
    'stageType' : IDL.Text,
  });
  const WorkflowChain = IDL.Record({
    'stages' : IDL.Vec(WorkflowStage),
    'medicine' : IDL.Opt(IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text })),
  });
  const LogExportRequest = IDL.Record({
    'status' : IDL.Text,
    'userRole' : IDL.Text,
    'errorMessage' : IDL.Opt(IDL.Text),
    'fileSizeBytes' : IDL.Opt(IDL.Nat),
    'exportType' : IDL.Text,
    'fileType' : IDL.Text,
    'filename' : IDL.Text,
    'filtersApplied' : IDL.Text,
  });
  const AuditSearchQuery = IDL.Record({
    'toTimestamp' : IDL.Opt(IDL.Int),
    'fromTimestamp' : IDL.Opt(IDL.Int),
    'role' : IDL.Opt(IDL.Text),
    'offset' : IDL.Nat,
    'limit' : IDL.Nat,
    'searchText' : IDL.Opt(IDL.Text),
    'severity' : IDL.Opt(IDL.Text),
    'eventType' : IDL.Opt(IDL.Text),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createAppointment' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Text],
        [IDL.Variant({ 'ok' : Appointment, 'err' : IDL.Text })],
        [],
      ),
    'createDiagnosticBooking' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : DiagnosticBooking, 'err' : IDL.Text })],
        [],
      ),
    'createInventoryItem' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Int, MedicineCategory],
        [IDL.Variant({ 'ok' : InventoryItem, 'err' : IDL.Text })],
        [],
      ),
    'createMedicine' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int, MedicineCategory],
        [IDL.Variant({ 'ok' : Medicine, 'err' : IDL.Text })],
        [],
      ),
    'createOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : Order, 'err' : IDL.Text })],
        [],
      ),
    'createReminder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : Reminder, 'err' : IDL.Text })],
        [],
      ),
    'createReport' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Report, 'err' : IDL.Text })],
        [],
      ),
    'deleteExportLog' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteInventoryItem' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteMedicine' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteReminder' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getAdherenceScore' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'getAllExportLogs' : IDL.Func([], [IDL.Vec(ExportLogEntry)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAuditEventsByActor' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ActivityEventView)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getConsentAuditTrail' : IDL.Func(
        [],
        [IDL.Vec(ConsentAuditEntry)],
        ['query'],
      ),
    'getConsentedPatients' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({ 'patient' : UserProfile, 'consent' : ConsentRecord })
          ),
        ],
        ['query'],
      ),
    'getDiagnosticBooking' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DiagnosticBooking)],
        ['query'],
      ),
    'getEventById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ActivityEventView)],
        ['query'],
      ),
    'getExpiryStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'expiringSoon' : IDL.Nat,
            'expired' : IDL.Nat,
            'safe' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getExportAnalytics' : IDL.Func(
        [],
        [
          IDL.Record({
            'successCount' : IDL.Nat,
            'failureCount' : IDL.Nat,
            'totalExports' : IDL.Nat,
            'exportsByRole' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
            'exportsByType' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
            'exportsByFormat' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          }),
        ],
        ['query'],
      ),
    'getInventoryStats' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getLabDiagnosticBookings' : IDL.Func(
        [],
        [IDL.Vec(DiagnosticBooking)],
        ['query'],
      ),
    'getLabReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'getMedicineLcChain' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ActivityEventView)],
        ['query'],
      ),
    'getMyConsent' : IDL.Func([], [IDL.Opt(ConsentRecord)], ['query']),
    'getMyDiagnosticBookings' : IDL.Func(
        [],
        [IDL.Vec(DiagnosticBooking)],
        ['query'],
      ),
    'getMyDoseLogs' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(DoseLog)],
        ['query'],
      ),
    'getMyExportLogs' : IDL.Func([], [IDL.Vec(ExportLogEntry)], ['query']),
    'getMyMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
    'getMyNotifications' : IDL.Func(
        [],
        [IDL.Vec(NotificationRecord)],
        ['query'],
      ),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getMyProfile' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        ['query'],
      ),
    'getMyReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
    'getMyReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'getMySyncedMedicines' : IDL.Func([], [IDL.Vec(SyncedMedicine)], ['query']),
    'getMyTimeline' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ActivityEventView)],
        ['query'],
      ),
    'getPharmacyInventory' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getPharmacyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getPharmacySyncLogs' : IDL.Func([], [IDL.Vec(PharmacySyncLog)], ['query']),
    'getReportData' : IDL.Func([IDL.Text], [ReportData], ['query']),
    'getSystemStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalOrders' : IDL.Nat,
            'totalUsers' : IDL.Nat,
            'totalMedicines' : IDL.Nat,
            'usersByRole' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          }),
        ],
        ['query'],
      ),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTelegramLogs' : IDL.Func([], [IDL.Vec(TelegramLog)], ['query']),
    'getWorkflowChain' : IDL.Func([IDL.Text], [WorkflowChain], ['query']),
    'isBotTokenConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logDose' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Bool],
        [IDL.Variant({ 'ok' : DoseLog, 'err' : IDL.Text })],
        [],
      ),
    'logExport' : IDL.Func([LogExportRequest], [ExportLogEntry], []),
    'lookupPatientByPhone' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'principal' : IDL.Principal,
              'name' : IDL.Text,
            }),
            'err' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'markAllNotificationsRead' : IDL.Func([], [IDL.Nat], []),
    'markEventRead' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'markNotificationRead' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, UserRole],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        [],
      ),
    'revokeAllConsent' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : ConsentRecord, 'err' : IDL.Text })],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchAuditLog' : IDL.Func(
        [AuditSearchQuery],
        [IDL.Vec(ActivityEventView)],
        ['query'],
      ),
    'sendTestTelegramMessage' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setBotToken' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'syncMedicineToPatient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Nat],
        [IDL.Variant({ 'ok' : PharmacySyncLog, 'err' : IDL.Text })],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAppointmentStatus' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Appointment, 'err' : IDL.Text })],
        [],
      ),
    'updateConsent' : IDL.Func(
        [IDL.Bool, IDL.Bool, IDL.Bool],
        [IDL.Variant({ 'ok' : ConsentRecord, 'err' : IDL.Text })],
        [],
      ),
    'updateDiagnosticBookingStatus' : IDL.Func(
        [IDL.Text, BookingStatus, IDL.Text],
        [IDL.Variant({ 'ok' : DiagnosticBooking, 'err' : IDL.Text })],
        [],
      ),
    'updateInventoryItem' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Int],
        [IDL.Variant({ 'ok' : InventoryItem, 'err' : IDL.Text })],
        [],
      ),
    'updateMedicine' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int, MedicineCategory],
        [IDL.Variant({ 'ok' : Medicine, 'err' : IDL.Text })],
        [],
      ),
    'updateMedicinePrescriptionUrl' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateOrderStatus' : IDL.Func(
        [IDL.Text, OrderStatus],
        [IDL.Variant({ 'ok' : Order, 'err' : IDL.Text })],
        [],
      ),
    'updateReminder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool, IDL.Bool],
        [IDL.Variant({ 'ok' : Reminder, 'err' : IDL.Text })],
        [],
      ),
    'updateTelegramSettings' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Bool)],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        [],
      ),
    'updateUserProfile' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Bool),
        ],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        [],
      ),
    'updateUserStatus' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'uploadDiagnosticReport' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : DiagnosticBooking, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };