/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ActivityActorRole = { 'Diagnostic' : null } |
  { 'Pharmacy' : null } |
  { 'Admin' : null } |
  { 'Patient' : null } |
  { 'Hospital' : null };
export type ActivityEventType = { 'ConsentGranted' : null } |
  { 'ReportCompleted' : null } |
  { 'SystemAlert' : null } |
  { 'InventoryStatusChanged' : null } |
  { 'DiagnosticBooked' : null } |
  { 'ConsentAccessGranted' : null } |
  { 'PatientAdherenceViewed' : null } |
  { 'RestockFulfilled' : null } |
  { 'ReminderCreated' : null } |
  { 'ReportUploaded' : null } |
  { 'TestProcessingStarted' : null } |
  { 'TelegramDisconnected' : null } |
  { 'HospitalMedicineAdded' : null } |
  { 'ReminderMissed' : null } |
  { 'HospitalInventoryUpdated' : null } |
  { 'CSVUploaded' : null } |
  { 'TelegramConnected' : null } |
  { 'BookingAccepted' : null } |
  { 'MedicineAddedManually' : null } |
  { 'BookingReceived' : null } |
  { 'ExpiryAlertTriggered' : null } |
  { 'ExpiryWarningTriggered' : null } |
  { 'ConsentRevoked' : null } |
  { 'EcosystemSyncStats' : null } |
  { 'DoseMarkedTaken' : null } |
  { 'UserCreated' : null } |
  { 'ConsentAccessRevoked' : null } |
  { 'MedicineSold' : null } |
  { 'MedicineSyncedToPatient' : null } |
  { 'RoleChanged' : null } |
  { 'ReportViewedDownloaded' : null } |
  { 'ReminderCompleted' : null } |
  { 'InventoryItemAdded' : null } |
  { 'SampleCollected' : null } |
  { 'MedicineSyncedFromPharmacy' : null } |
  { 'QRScanCompleted' : null };
export interface ActivityEventView {
  'id' : string,
  'metadata' : [] | [string],
  'resourceId' : [] | [string],
  'eventActor' : { 'role' : ActivityActorRole, 'principalId' : Principal },
  'timestamp' : bigint,
  'eventType' : ActivityEventType,
  'readBy' : Array<Principal>,
}
export interface Appointment {
  'id' : string,
  'status' : string,
  'notes' : string,
  'patientName' : string,
  'dateTime' : Timestamp,
}
export interface AuditSearchQuery {
  'toTimestamp' : [] | [bigint],
  'fromTimestamp' : [] | [bigint],
  'role' : [] | [string],
  'offset' : bigint,
  'limit' : bigint,
  'searchText' : [] | [string],
  'severity' : [] | [string],
  'eventType' : [] | [string],
}
export type BookingStatus = { 'ReportUploaded' : null } |
  { 'Confirmed' : null } |
  { 'Booked' : null } |
  { 'InProgress' : null } |
  { 'Completed' : null };
export interface BookingStatusEntry {
  'status' : BookingStatus,
  'note' : string,
  'timestamp' : Timestamp,
}
export interface ConsentAuditEntry {
  'field' : string,
  'action' : string,
  'timestamp' : Timestamp,
}
export interface ConsentRecord {
  'id' : string,
  'lastUpdated' : Timestamp,
  'adherenceSharing' : boolean,
  'patientPrincipal' : Principal,
  'diagnosticAccess' : boolean,
  'auditTrail' : Array<ConsentAuditEntry>,
  'prescriptionSharing' : boolean,
}
export interface DiagnosticBooking {
  'id' : string,
  'reportUrl' : [] | [string],
  'status' : BookingStatus,
  'createdAt' : Timestamp,
  'testType' : string,
  'statusHistory' : Array<BookingStatusEntry>,
  'reportUploadedAt' : [] | [Timestamp],
  'patientPrincipal' : Principal,
  'preferredDate' : string,
  'labPrincipal' : Principal,
  'reason' : [] | [string],
}
export interface DoseLog {
  'id' : string,
  'isOnTime' : boolean,
  'takenAt' : Timestamp,
  'userPrincipal' : Principal,
  'medicineId' : string,
}
export interface ExportLogEntry {
  'id' : string,
  'status' : string,
  'userRole' : string,
  'userId' : Principal,
  'errorMessage' : [] | [string],
  'fileSizeBytes' : [] | [bigint],
  'exportType' : string,
  'fileType' : string,
  'filename' : string,
  'timestamp' : bigint,
  'filtersApplied' : string,
}
export interface InventoryItem {
  'id' : string,
  'stockQuantity' : bigint,
  'expiryDate' : Timestamp,
  'minThreshold' : bigint,
  'lastUpdated' : Timestamp,
  'pharmacyPrincipal' : Principal,
  'category' : MedicineCategory,
  'maxThreshold' : bigint,
  'medicineName' : string,
}
export interface LogExportRequest {
  'status' : string,
  'userRole' : string,
  'errorMessage' : [] | [string],
  'fileSizeBytes' : [] | [bigint],
  'exportType' : string,
  'fileType' : string,
  'filename' : string,
  'filtersApplied' : string,
}
export interface Medicine {
  'id' : string,
  'dosage' : string,
  'expiryDate' : Timestamp,
  'ownerPrincipal' : Principal,
  'name' : string,
  'createdAt' : Timestamp,
  'category' : MedicineCategory,
  'frequency' : string,
  'prescriptionUrl' : [] | [string],
}
export type MedicineCategory = { 'Liquid' : null } |
  { 'Capsule' : null } |
  { 'Injection' : null } |
  { 'Tablet' : null } |
  { 'Topical' : null } |
  { 'Other' : null };
export type NotifType = { 'BookingCompleted' : null } |
  { 'ConsentChanged' : null } |
  { 'ReminderMissed' : null } |
  { 'ReportReady' : null } |
  { 'MedicineSynced' : null } |
  { 'BookingConfirmed' : null } |
  { 'LowStock' : null } |
  { 'ExpiringSoon' : null };
export interface NotificationRecord {
  'id' : string,
  'notifType' : NotifType,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'isRead' : boolean,
  'message' : string,
  'relatedId' : [] | [string],
  'recipientPrincipal' : Principal,
}
export interface Order {
  'id' : string,
  'status' : OrderStatus,
  'patientId' : string,
  'deliveryDate' : [] | [Timestamp],
  'orderDate' : Timestamp,
  'quantity' : bigint,
  'pharmacyId' : string,
  'medicineName' : string,
}
export type OrderStatus = { 'Delivered' : null } |
  { 'Cancelled' : null } |
  { 'Shipped' : null } |
  { 'Pending' : null };
export interface PharmacySyncLog {
  'id' : string,
  'status' : { 'Failed' : null } |
    { 'Duplicate' : null } |
    { 'Success' : null },
  'expiryDate' : Timestamp,
  'errorMessage' : [] | [string],
  'pharmacyPrincipal' : Principal,
  'patientPrincipal' : Principal,
  'syncedAt' : Timestamp,
  'batchNumber' : string,
  'quantity' : bigint,
  'medicineName' : string,
}
export interface Reminder {
  'id' : string,
  'createdAt' : Timestamp,
  'voiceEnabled' : boolean,
  'isEnabled' : boolean,
  'reminderTime' : string,
  'userPrincipal' : Principal,
  'medicineId' : string,
}
export interface Report {
  'id' : string,
  'patientId' : string,
  'reportType' : string,
  'uploadDate' : Timestamp,
  'labPrincipal' : Principal,
  'fileUrl' : string,
}
export interface ReportData {
  'generatedAt' : bigint,
  'reportType' : string,
  'dataPoints' : Array<ReportDataPoint>,
}
export interface ReportDataPoint {
  'value' : string,
  'metadata' : [] | [string],
  'dataLabel' : string,
}
export interface SyncedMedicine {
  'id' : string,
  'sourcePharmacy' : string,
  'dosage' : string,
  'purchaseTimestamp' : Timestamp,
  'expiryDate' : Timestamp,
  'ownerPrincipal' : Principal,
  'name' : string,
  'createdAt' : Timestamp,
  'batchNumber' : string,
  'category' : MedicineCategory,
  'frequency' : string,
  'sourcePrincipal' : Principal,
  'prescriptionUrl' : [] | [string],
}
export interface TelegramLog {
  'id' : string,
  'status' : string,
  'errorMessage' : [] | [string],
  'reminderTime' : string,
  'userPrincipal' : Principal,
  'timestamp' : bigint,
  'medicineId' : string,
  'medicineName' : string,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'id' : string,
  'principal' : Principal,
  'name' : string,
  'role' : UserRole,
  'isActive' : boolean,
  'email' : string,
  'telegramEnabled' : boolean,
  'phone' : [] | [string],
  'registrationDate' : Timestamp,
  'telegramChatId' : [] | [string],
}
export type UserRole = { 'Lab' : null } |
  { 'Pharmacy' : null } |
  { 'Admin' : null } |
  { 'Patient' : null } |
  { 'Hospital' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkflowChain {
  'stages' : Array<WorkflowStage>,
  'medicine' : [] | [{ 'id' : string, 'name' : string }],
}
export interface WorkflowStage {
  'status' : string,
  'actorRole' : string,
  'events' : Array<ActivityEventView>,
  'stageType' : string,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createAppointment' : ActorMethod<
    [string, bigint, string],
    { 'ok' : Appointment } |
      { 'err' : string }
  >,
  'createDiagnosticBooking' : ActorMethod<
    [Principal, string, string, [] | [string]],
    { 'ok' : DiagnosticBooking } |
      { 'err' : string }
  >,
  'createInventoryItem' : ActorMethod<
    [string, bigint, bigint, bigint, bigint, MedicineCategory],
    { 'ok' : InventoryItem } |
      { 'err' : string }
  >,
  'createMedicine' : ActorMethod<
    [string, string, string, bigint, MedicineCategory],
    { 'ok' : Medicine } |
      { 'err' : string }
  >,
  'createOrder' : ActorMethod<
    [string, string, string, bigint],
    { 'ok' : Order } |
      { 'err' : string }
  >,
  'createReminder' : ActorMethod<
    [string, string, boolean],
    { 'ok' : Reminder } |
      { 'err' : string }
  >,
  'createReport' : ActorMethod<
    [string, string, string],
    { 'ok' : Report } |
      { 'err' : string }
  >,
  'deleteExportLog' : ActorMethod<[string], boolean>,
  'deleteInventoryItem' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteMedicine' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteReminder' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getAdherenceScore' : ActorMethod<[string], number>,
  'getAllExportLogs' : ActorMethod<[], Array<ExportLogEntry>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAuditEventsByActor' : ActorMethod<[string], Array<ActivityEventView>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getConsentAuditTrail' : ActorMethod<[], Array<ConsentAuditEntry>>,
  'getConsentedPatients' : ActorMethod<
    [],
    Array<{ 'patient' : UserProfile, 'consent' : ConsentRecord }>
  >,
  'getDiagnosticBooking' : ActorMethod<[string], [] | [DiagnosticBooking]>,
  'getEventById' : ActorMethod<[string], [] | [ActivityEventView]>,
  'getExpiryStats' : ActorMethod<
    [],
    { 'expiringSoon' : bigint, 'expired' : bigint, 'safe' : bigint }
  >,
  'getExportAnalytics' : ActorMethod<
    [],
    {
      'successCount' : bigint,
      'failureCount' : bigint,
      'totalExports' : bigint,
      'exportsByRole' : Array<[string, bigint]>,
      'exportsByType' : Array<[string, bigint]>,
      'exportsByFormat' : Array<[string, bigint]>,
    }
  >,
  'getInventoryStats' : ActorMethod<[], Array<[string, bigint]>>,
  'getLabDiagnosticBookings' : ActorMethod<[], Array<DiagnosticBooking>>,
  'getLabReports' : ActorMethod<[], Array<Report>>,
  'getMedicineLcChain' : ActorMethod<[string], Array<ActivityEventView>>,
  'getMyConsent' : ActorMethod<[], [] | [ConsentRecord]>,
  'getMyDiagnosticBookings' : ActorMethod<[], Array<DiagnosticBooking>>,
  'getMyDoseLogs' : ActorMethod<[[] | [string]], Array<DoseLog>>,
  'getMyExportLogs' : ActorMethod<[], Array<ExportLogEntry>>,
  'getMyMedicines' : ActorMethod<[], Array<Medicine>>,
  'getMyNotifications' : ActorMethod<[], Array<NotificationRecord>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getMyProfile' : ActorMethod<[], { 'ok' : UserProfile } | { 'err' : string }>,
  'getMyReminders' : ActorMethod<[], Array<Reminder>>,
  'getMyReports' : ActorMethod<[], Array<Report>>,
  'getMySyncedMedicines' : ActorMethod<[], Array<SyncedMedicine>>,
  'getMyTimeline' : ActorMethod<[bigint, bigint], Array<ActivityEventView>>,
  'getPharmacyInventory' : ActorMethod<[], Array<InventoryItem>>,
  'getPharmacyOrders' : ActorMethod<[], Array<Order>>,
  'getPharmacySyncLogs' : ActorMethod<[], Array<PharmacySyncLog>>,
  'getReportData' : ActorMethod<[string], ReportData>,
  'getSystemStats' : ActorMethod<
    [],
    {
      'totalOrders' : bigint,
      'totalUsers' : bigint,
      'totalMedicines' : bigint,
      'usersByRole' : Array<[string, bigint]>,
    }
  >,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTelegramLogs' : ActorMethod<[], Array<TelegramLog>>,
  'getWorkflowChain' : ActorMethod<[string], WorkflowChain>,
  'isBotTokenConfigured' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logDose' : ActorMethod<
    [string, bigint, boolean],
    { 'ok' : DoseLog } |
      { 'err' : string }
  >,
  'logExport' : ActorMethod<[LogExportRequest], ExportLogEntry>,
  'lookupPatientByPhone' : ActorMethod<
    [string],
    { 'ok' : { 'principal' : Principal, 'name' : string } } |
      { 'err' : string }
  >,
  'markAllNotificationsRead' : ActorMethod<[], bigint>,
  'markEventRead' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'markNotificationRead' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'registerUser' : ActorMethod<
    [string, string, UserRole],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
  'revokeAllConsent' : ActorMethod<
    [],
    { 'ok' : ConsentRecord } |
      { 'err' : string }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchAuditLog' : ActorMethod<[AuditSearchQuery], Array<ActivityEventView>>,
  'sendTestTelegramMessage' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setBotToken' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'syncMedicineToPatient' : ActorMethod<
    [string, string, string, bigint, bigint],
    { 'ok' : PharmacySyncLog } |
      { 'err' : string }
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAppointmentStatus' : ActorMethod<
    [string, string],
    { 'ok' : Appointment } |
      { 'err' : string }
  >,
  'updateConsent' : ActorMethod<
    [boolean, boolean, boolean],
    { 'ok' : ConsentRecord } |
      { 'err' : string }
  >,
  'updateDiagnosticBookingStatus' : ActorMethod<
    [string, BookingStatus, string],
    { 'ok' : DiagnosticBooking } |
      { 'err' : string }
  >,
  'updateInventoryItem' : ActorMethod<
    [string, bigint, bigint, bigint, bigint],
    { 'ok' : InventoryItem } |
      { 'err' : string }
  >,
  'updateMedicine' : ActorMethod<
    [string, string, string, string, bigint, MedicineCategory],
    { 'ok' : Medicine } |
      { 'err' : string }
  >,
  'updateMedicinePrescriptionUrl' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateOrderStatus' : ActorMethod<
    [string, OrderStatus],
    { 'ok' : Order } |
      { 'err' : string }
  >,
  'updateReminder' : ActorMethod<
    [string, string, boolean, boolean],
    { 'ok' : Reminder } |
      { 'err' : string }
  >,
  'updateTelegramSettings' : ActorMethod<
    [[] | [string], [] | [boolean]],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
  'updateUserProfile' : ActorMethod<
    [[] | [string], [] | [string], [] | [string], [] | [boolean]],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
  'updateUserStatus' : ActorMethod<
    [string, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'uploadDiagnosticReport' : ActorMethod<
    [string, string],
    { 'ok' : DiagnosticBooking } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];